version: "3"
services:
  postgres:
    image: "postgres:14"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: odk
      POSTGRES_PASSWORD: odk
      POSTGRES_DB: odk
    restart: always
  mail:
    image: "itsissa/namshi-smtp:4.92-8.deb10u6"
    volumes:
      - ./files/dkim/config:/etc/exim4/_docker_additional_macros:ro
      - ./files/dkim/rsa.private:/etc/exim4/domain.key:ro
    environment:
      - MAILNAME=${DOMAIN}
    restart: always
  service:
    image: "lalithkota/odk-central-backend:1.5.3"
    depends_on:
      - postgres
      - mail
      - pyxform
      - enketo
    environment:
      - DOMAIN=${DOMAIN}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - SYSADMIN_EMAIL=${SYSADMIN_EMAIL}
      - ENKETO_API_KEY=${ENKETO_API_KEY}
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "./start-odk.sh" ]
    restart: always
    logging:
      driver: local
  nginx:
    image: "lalithkota/odk-central-frontend:1.5.3"
    depends_on:
      - service
      - enketo
    ports:
      - 8333:${HTTP_PORT:-80}
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 80 || exit 1" ]
    restart: always
    logging:
      driver: local
      options:
        max-file: "30"
  pyxform:
    image: 'ghcr.io/getodk/pyxform-http:v1.10.1.1'
    restart: always
  enketo:
    image: "lalithkota/odk-central-enketo:1.5.3"
    restart: always
    depends_on:
      - enketo_redis_main
      - enketo_redis_cache
    environment:
      - DOMAIN=${DOMAIN}
      - SUPPORT_EMAIL=${SYSADMIN_EMAIL}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - ENKETO_API_KEY=${ENKETO_API_KEY}
      - ENKETO_SECRET=${ENKETO_SECRET}
      - ENKETO_LESS_SECRET=${ENKETO_LESS_SECRET}
  enketo_redis_main:
    image: redis:5
    volumes:
      - ./files/enketo/redis-enketo-main.conf:/usr/local/etc/redis/redis.conf:ro
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always
  enketo_redis_cache:
    image: redis:5
    volumes:
      - ./files/enketo/redis-enketo-cache.conf:/usr/local/etc/redis/redis.conf:ro
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always
