apiVersion: v1
kind: Service
metadata:
  name: odk-central-backend
  labels:
    app.kubernetes.io/name: odk-central-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app.kubernetes.io/name: odk-central-backend
