{{- if .Values.istio.enabled  }}
{{- if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: odk-central
  labels:
    app.kubernetes.io/name: odk-central
spec:
  selector:
    {{ toYaml .Values.istio.gateway.ingressController | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ .Values.istio.gateway.host }}
    {{- if .Values.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      - {{ .Values.istio.gateway.host }}
    {{- if .Values.istio.gateway.tls.enabled }}
    tls:
      {{ toYaml (omit .Values.istio.gateway.tls "enabled") | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
