{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: odk-central
  labels:
    app.kubernetes.io/name: odk-central
spec:
  hosts:
  - "*"
  gateways:
    {{- if .Values.istio.existingGateway }}
    - {{ .Values.istio.existingGateway }}
    {{- else }}
    - {{ template "common.names.fullname" . }}
    {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: odk-central-frontend
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https
{{- end }}
