{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: odk-central
  labels:
    app.kubernetes.io/name: odk-central
spec:
  hosts:
  - {{ .Values.istio.virtualservice.host }}
  gateways:
    {{- if not .Values.istio.virtualservice.gateway }}
    - odk-central
    {{- else }}
    - {{ .Values.istio.virtualservice.gateway }}
    {{- end }}
  http:
  - route:
    - destination:
        host: odk-central-frontend
        port:
          number: 80
{{- end }}
{{- end }}
