replicaCount: 1

service:
  type: ClusterIP
  port: 80

image:
  registry: docker.io
  repository: lalithkota/odk-central-enketo
  tag: 1.5.3
  pullPolicy: Always

containerPort: 8005

startupProbe:
  enabled: true
  tcpSocket:
    port: 8005
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1

livenessProbe:
  enabled: true
  tcpSocket:
    port: 8005
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  enabled: true
  tcpSocket:
    port: 8005
  initialDelaySeconds: 0
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

command: []
args: []

resources:
  limits: {}
  #   cpu: 200m
  #   memory: 256Mi
  requests: {}
  #   cpu: 100m
  #   memory: 1500Mi

containerSecurityContext:
  enabled: false
  runAsUser: odk
  runAsNonRoot: true

podSecurityContext:
  enabled: false
  fsGroup: 1001

extraEnvVars: []

extraEnvVarsCM: []

extraEnvVarsSecret: []

redis:
  main:
    host: "enketo-redis-main"
    port: "6379"
  cache:
    host: "enketo-redis-cache"
    port: "6380"
