apiVersion: v2
name: odk-central-mail
description: A Helm chart for odk-central-mail.
type: application
version: 0.1.0
appVersion: ""
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
   - bitnami-common
  version: 1.x.x
keywords:
  - odk
  - odk-central
  - odk-central-mail
maintainers:
  - email: kotalalith@gmail.com
    name: lalithkota
