apiVersion: v1
kind: Service
metadata:
  name: enketo-redis-main
  labels:
    app.kubernetes.io/name: enketo-redis-main
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp-redis
      port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: enketo-redis-main
