apiVersion: v1
kind: Secret
metadata:
  name: odk-central-enketo
type: Opaque
data:
  ENKETO_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
  ENKETO_LESS_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  ENKETO_API_KEY: {{ randAlphaNum 128 | b64enc | quote }}