domain: &domain ""

odk-central-mail:
  enabled: true
  mailName: *domain
odk-central-pyxform:
  enabled: true
odk-central-enketo:
  enabled: true
odk-central-backend:
  enabled: true
  domain: *domain
odk-central-frontend:
  enabled: true

ingress:
  enabled: false
  ingressClassName: ""
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: *domain
  annotations: {}
  tls: false
  selfSigned: false
  extraPaths: []
  extraTls: []
  secrets: []

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: *domain
    gateway: ""
  gateway:
    enabled: true
    host: *domain
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    tls:
      enabled: true
      mode: SIMPLE
      credentialName: ""
